
// https://github.com/benjamincanac.png

export const organizers = [
  {
    id: 'Tech Innovators Inc.',
    name: 'Tech Innovators Inc.',
    ava: 'https://github.com/benjamincanac.png',
    link: '/organizers/tech-innovators',
    rating: {
      count: 100,
      value: 4.8,
    },
  },
  {
    id: 'Artistic Minds Studio',
    name: 'Artistic Minds Studio',
    ava: 'https://github.com/benjamincanac.png',
    link: '/organizers/artistic-minds',
    rating: {
      count: 100,
      value: 4.8,
    },
  },
  {
    id: 'Green Thumb Community',
    name: 'Green Thumb Community',
    ava: 'https://github.com/benjamincanac.png',
    link: '/organizers/green-thumb',
    rating: {
      count: 100,
      value: 4.8,
    },
  },
  {
    id: 'Fitness Fanatics Club',
    name: 'Fitness Fanatics Club',
    ava: 'https://github.com/benjamincanac.png',
    link: '/organizers/fitness-fanatics',
    rating: {
      count: 100,
      value: 4.8,
    },
  },
] as TGamesCalendarOrg[];

const techInnovators = organizers[0];
const artisticMinds = organizers[1];
const greenThumb = organizers[2];
const fitnessFanatics = organizers[3];

export const events = [
  {
    id: 'Frontend Masterclass 2025',
    name: 'Frontend Masterclass 2025',
    addInfo: 'Глубокое погружение в Vue 3 и Nuxt 3.',
    maxUsers: 100,
    currentUsers: 75,
    cost: '€199',
    time: '2025-08-10 09:00',
    link: '/techInnovators',
    org: techInnovators,
  },
  {
    id: 'AI in Web Development Workshop',
    name: 'AI in Web Development Workshop',
    maxUsers: 50,
    currentUsers: 40,
    cost: '€250',
    time: '2025-08-15 14:00',
    link: '/techInnovators',
    org: techInnovators,
  },
  {
    id: 'JavaScript Performance Optimization',
    name: 'JavaScript Performance Optimization',
    currentUsers: 30,
    cost: 'Free',
    time: '2025-08-20 18:00',
    link: '/techInnovators',
    org: techInnovators,
  },
  {
    id: 'Nuxt UI & TailwindCSS Best Practices',
    name: 'Nuxt UI & TailwindCSS Best Practices',
    addInfo: 'Практический семинар по созданию красивых интерфейсов.',
    maxUsers: 80,
    currentUsers: 60,
    cost: '€150',
    time: '2025-08-25 10:00',
    link: '/techInnovators',
    org: techInnovators,
  },
  {
    id: 'Modern CSS Techniques',
    name: 'Modern CSS Techniques',
    currentUsers: 25,
    cost: '€99',
    time: '2025-09-01 11:00',
    link: '/techInnovators',
    org: techInnovators,
  },
  {
    id: 'Digital Art Marathon',
    name: 'Digital Art Marathon',
    addInfo: 'Создайте свой шедевр за 24 часа.',
    maxUsers: 30,
    currentUsers: 28,
    cost: '€120',
    time: '2025-09-05 09:00',
    link: '/artisticMinds',
    org: artisticMinds,
  },
  {
    id: 'Figure Drawing Basics',
    name: 'Figure Drawing Basics',
    maxUsers: 20,
    currentUsers: 15,
    cost: '€80',
    time: '2025-09-10 17:00',
    link: '/artisticMinds',
    org: artisticMinds,
  },
  {
    id: 'Creative Writing Workshop',
    name: 'Creative Writing Workshop',
    currentUsers: 10,
    cost: '€70',
    time: '2025-09-12 19:00',
    link: '/artisticMinds',
    org: artisticMinds,
  },
  {
    id: 'Photography for Beginners',
    name: 'Photography for Beginners',
    addInfo: 'Основы композиции и обработки.',
    maxUsers: 25,
    currentUsers: 20,
    cost: '€110',
    time: '2025-09-18 10:00',
    link: '/artisticMinds',
    org: artisticMinds,
  },
  {
    id: 'Sculpture from Recycled Materials',
    name: 'Sculpture from Recycled Materials',
    currentUsers: 8,
    cost: '€90',
    time: '2025-09-22 14:00',
    link: '/artisticMinds',
    org: artisticMinds,
  },
  {
    id: 'Urban Gardening for Small Spaces',
    name: 'Urban Gardening for Small Spaces',
    addInfo: 'Выращивайте свежие продукты на балконе.',
    maxUsers: 40,
    currentUsers: 35,
    cost: 'Free',
    time: '2025-10-01 16:00',
    link: '/greenThumb',
    org: greenThumb,
  },
  {
    id: 'Composting at Home',
    name: 'Composting at Home',
    currentUsers: 20,
    cost: 'Free',
    time: '2025-10-05 11:00',
    link: '/greenThumb',
    org: greenThumb,
  },
  {
    id: 'Tree Planting Day',
    name: 'Tree Planting Day',
    maxUsers: 200,
    currentUsers: 180,
    cost: 'Free',
    time: '2025-10-10 09:00',
    link: '/greenThumb',
    org: greenThumb,
  },
  {
    id: 'Sustainable Living Workshop',
    name: 'Sustainable Living Workshop',
    addInfo: 'Советы по уменьшению углеродного следа.',
    currentUsers: 50,
    cost: '€50',
    time: '2025-10-15 13:00',
    link: '/greenThumb',
    org: greenThumb,
  },
  {
    id: 'DIY Hydroponics Systems',
    name: 'DIY Hydroponics Systems',
    maxUsers: 15,
    currentUsers: 12,
    cost: '€75',
    time: '2025-10-20 18:00',
    link: '/greenThumb',
    org: greenThumb,
  },
  {
    id: 'High-Intensity Interval Training (HIIT)',
    name: 'High-Intensity Interval Training (HIIT)',
    addInfo: 'Тренировка для всех уровней подготовки.',
    maxUsers: 20,
    currentUsers: 18,
    cost: '€20',
    time: '2025-11-01 08:00',
    link: '/fitnessFanatics',
    org: fitnessFanatics,
  },
  {
    id: 'Yoga for Stress Relief',
    name: 'Yoga for Stress Relief',
    currentUsers: 25,
    cost: '€15',
    time: '2025-11-05 19:00',
    link: '/fitnessFanatics',
    org: fitnessFanatics,
  },
  {
    id: 'Marathon Training Group',
    name: 'Marathon Training Group',
    maxUsers: 30,
    currentUsers: 22,
    cost: '€100',
    time: '2025-11-10 07:00',
    link: '/fitnessFanatics',
    org: fitnessFanatics,
  },
  {
    id: 'Nutritional Planning for Athletes',
    name: 'Nutritional Planning for Athletes',
    addInfo: 'Оптимизация питания для достижения лучших результатов.',
    currentUsers: 15,
    cost: '€60',
    time: '2025-11-15 16:00',
    link: '/fitnessFanatics',
    org: fitnessFanatics,
  },
  {
    id: 'Pilates Core Strength',
    name: 'Pilates Core Strength',
    maxUsers: 18,
    currentUsers: 10,
    cost: '€25',
    time: '2025-11-20 12:00',
    link: '/fitnessFanatics',
    org: fitnessFanatics,
  },
] as TGamesCalendarEvent[];

export const eventsFromPlaces = {
  online: events,
  Minsk: events,
  Pinsk: events
} as Record<string, TGamesCalendarEvent[]>