/**
 * This file was auto-generated by scripts/formate-api.mjs.
 * Do not make direct changes to the file.
 */

export const AUTH = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  VERIFY_EMAIL: "/auth/verify-email",
  ME: "/auth/me",
  LOGOUT: "/auth/logout",
  REFRESH: "/auth/refresh",
  RESET_PASSWORD_REQUEST: "/auth/reset-password/request",
  RESET_PASSWORD_VALIDATE: "/auth/reset-password/validate",
  RESET_PASSWORD_CONFIRM: "/auth/reset-password/confirm",
} as const;

export const PROFILE = {
  ME: "/profile/me",
  ID: "/profile/",
} as const;

export const ORG = {
  CREATE: "/org/create",
  INDEX: "/org",
  ME: "/org/me",
  SLUG: "/org/",
} as const;

export const EVENTS = {
  INDEX: "/events",
  SLUG: "/events/",
  ID: "/events/",
  ID_CANCEL: "/events/{id}/cancel",
} as const;

export const DICTIONARIES = {
  INDEX: "/dictionaries",
} as const;
