import fs from 'node:fs';
import path from 'node:path';

// 1. Извлечение пути к артефакту спецификации из .env
const envPath = path.resolve(process.cwd(), '.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split('\n').forEach((line) => {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (match) {
      const key = match[1];
      let value = match[2] || '';
      if (value.length > 0 && value.startsWith('"') && value.endsWith('"')) {
        value = value.slice(1, -1);
      }
      process.env[key] = value.trim();
    }
  });
}

const OPENAPI_PATH = process.env.OPENAPI_PATH || '../backend/openapi.json';
const catalogDir = './shared/open-api';

const GENERATED_HEADER = `/**
 * This file was auto-generated by scripts/formate-api.mjs.
 * Do not make direct changes to the file.
 */
`;

/**
 * @typedef {Object} MethodInfo
 * @property {string|null} reqContentType
 * @property {string|null} resContentType
 * @property {string|undefined} successCode
 */

try {
  console.log('Форматирование каталога OpenAPI...');

  const resolvedOpenapiPath = path.resolve(process.cwd(), OPENAPI_PATH);
  const specContent = fs.readFileSync(resolvedOpenapiPath, 'utf-8');
  const spec = JSON.parse(specContent);
  const paths = Object.keys(spec.paths);

  /** @type {Object.<string, Object.<string, { path: string, methods: Object.<string, MethodInfo> }>>} */
  const grouped = {};

  paths.forEach((path) => {
    const parts = path
      .split('/')
      .filter(Boolean)
      .map((part) => part.replace(/[{}]/g, ''));

    if (parts.length === 0) return;

    const group = parts[0].toUpperCase().replace(/-/g, '_');
    const key = parts.slice(1).join('_').toUpperCase().replace(/-/g, '_') || 'INDEX';

    if (!grouped[group]) grouped[group] = {};

    const methodsInfo = {};

    Object.entries(spec.paths[path]).forEach(([method, detail]) => {
      const m = method.toLowerCase();

      let reqContentType = null;
      if (detail.requestBody?.content) {
        const types = Object.keys(detail.requestBody.content);
        reqContentType = types.includes('application/json')
          ? 'application/json'
          : types.includes('multipart/form-data')
            ? 'multipart/form-data'
            : types[0];
      }

      const successCode = Object.keys(detail.responses || {}).find((code) => code.startsWith('2'));
      let resContentType = null;

      if (successCode && detail.responses[successCode]?.content) {
        const types = Object.keys(detail.responses[successCode].content);
        resContentType = types.includes('application/json')
          ? 'application/json'
          : types.includes('multipart/form-data')
            ? 'multipart/form-data'
            : types[0];
      }

      methodsInfo[m] = { reqContentType, resContentType, successCode };
    });

    grouped[group][key] = {
      path,
      methods: methodsInfo,
    };
  });

  const generateEndpointsFile = () => {
    const blocks = Object.entries(grouped)
      .map(([group, items]) => {
        const entries = Object.entries(items)
          .map(([key, info]) => {
            const cleanPath = info.path.replace(/\/{[^}]+}$/, '/');
            return `  ${key}: "${cleanPath}",`;
          })
          .join('\n');
        return `export const ${group} = {\n${entries}\n} as const;`;
      })
      .join('\n\n');

    return `${GENERATED_HEADER}\n${blocks}\n`;
  };

  const generateEnumsFile = () => {
    const schemas = spec.components?.schemas || {};
    const blocks = Object.entries(schemas)
      .filter(([_, schema]) => Array.isArray(schema.enum))
      .map(([name, schema]) => {
        return `export const ${name} = ${JSON.stringify(schema.enum)} as const;\nexport type ${name} = (typeof ${name})[number];`;
      })
      .join('\n\n');

    return `${GENERATED_HEADER}\n${blocks}\n`;
  };

  const generateTypesFile = () => {
    const blocks = Object.entries(grouped)
      .map(([group, items]) => {
        const entries = Object.entries(items)
          .map(([key, info]) => {
            const methodTypes = Object.entries(info.methods)
              .map(([m, details]) => {
                const methodUpper = m.toUpperCase();
                const reqTypeLine = details.reqContentType
                  ? `req: paths["${info.path}"]["${m}"]["requestBody"]["content"]["${details.reqContentType}"];`
                  : 'req?: never;';
                const resTypeLine = details.resContentType
                  ? `res: paths["${info.path}"]["${m}"]["responses"]["${details.successCode}"]["content"]["${details.resContentType}"];`
                  : 'res?: void;';

                return `    ${methodUpper}: {\n      ${reqTypeLine}\n      ${resTypeLine}\n    };`;
              })
              .join('\n');

            return `  ${key}: {\n${methodTypes}\n  };`;
          })
          .join('\n');

        return `export type ${group} = {\n${entries}\n};`;
      })
      .join('\n\n');

    return `${GENERATED_HEADER}
import type { components, paths } from './schema';

${blocks}

export type ApiPath = keyof paths;

export type TypePaginationMeta = components['schemas']['PaginationMetaDto'];
`.trimStart();
  };

  const generateIndexFile = () => {
    const names = Object.keys(grouped);
    const valueImport = names.join(', ');
    const typeImports = names.map((name) => `  ${name} as ${name}Type,`).join('\n');
    const typeAliases = names.map((name) => `export type ${name} = ${name}Type;`).join('\n');

    return `${GENERATED_HEADER}
import { ${valueImport} } from './api-endpoints';
import type {
${typeImports}
  ApiPath,
  TypePaginationMeta,
} from './types';

export { ${valueImport} };
${typeAliases}
export type { ApiPath, TypePaginationMeta };

export * from './enums';
`;
  };

  fs.mkdirSync(catalogDir, { recursive: true });
  fs.writeFileSync(path.join(catalogDir, 'api-endpoints.ts'), generateEndpointsFile());
  fs.writeFileSync(path.join(catalogDir, 'enums.ts'), generateEnumsFile());
  fs.writeFileSync(path.join(catalogDir, 'types.ts'), generateTypesFile());
  fs.writeFileSync(path.join(catalogDir, 'index.ts'), generateIndexFile());

  console.log(`Каталог OpenAPI обновлён в ${catalogDir}`);
} catch (error) {
  console.error('Произошла ошибка при генерации типов:', error.message || error);
  process.exit(1);
}
